### ISSUE TITLE
Running site-prerender on GitLab shared runner fails

### ISSUE THREAD

**Issue by jmbluethner** [dattran92/site-prerender#1]
Hey @dattran92 👋

I've just found out about site-prerender, and so far I really love it because it's super simple to use while also being super effective at what I need.
However, running it in on a shared GitLab runner brings up a problem.

# Setup

To start things off, I want to quickly tell you what my setup is.

A render stage in my .gitlab-ci.yml calls <code>npm run render</code>, which simply runs a small js file.  

```yml
render:
  stage: render
  script:
    - npm i
    - npm run render
```

```json
{
  "scripts": {
    "render": "node render.js"
  },
  "dependencies": {
    "site-prerender": "^1.0.1"
  }
}
```

```js
const SitePrerender = require('site-prerender')

const sp = new SitePrerender({
    staticPath: './src',
    outputFolder: './dist',
    routes: ['/']
})

async function exec() {
    await sp.init()
    await sp.start()
    await sp.close()
}

return exec();
```

# Problem description

Once the runner starts, it quickly quits with an error.

```
> node render.js
{"name":"site-prerender","hostname":"runner-xxurkrix-project-18966475-concurrent-0","pid":2103,"level":30,"msg":"Server started at http://localhost:3000/","time":"2022-04-26T11:26:56.078Z","v":0}
/builds/jmbluethner/heliophobix-relaunch/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241
            reject(new Error([
                   ^
Error: Failed to launch the browser process!
[0426/112656.117823:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/builds/jmbluethner/heliophobix-relaunch/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/builds/jmbluethner/heliophobix-relaunch/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (node:events:539:35)
    at Interface.close (node:internal/readline/interface:535:10)
    at Socket.onend (node:internal/readline/interface:261:10)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1344:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

# Cause of problem

The problem here is, that GitLab runners always run as root user. But chrome doesn't allow this without the <code>--no-sandbox</code> flag.  
See this part of the log:

```
Error: Failed to launch the browser process!
[0426/112656.117823:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
```

# Solution attempts

So now we know what the problem is, but I don't know how to solve that.  
My two ideas where:  
- Running the npm command without root privileges, which doesn't seem to be possible on shared runners
- Telling chrome to <b>always</b> run with the <code>--no-sandbox</code> flag. But that's not possible either afaik.

<hr>

I really want to use site-prerender in my CI/CD because it's exactly what I need, but this problem drives me crazy.  
Any help would be really appreciated!

Thanks in advance and have an awesome day everyone.

**Comment by jmbluethner** [comment]
@dattran92 I found a fix which you can adopt really easily.

In <code>/lib/crawler.js</code> change line 12 - 14 from  

```js
this.browser = await puppeteer.launch({
    headless: this.headless
})
```

to

```js
this.browser = await puppeteer.launch({
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
    headless: this.headless
});
```

Would love to see this in the next release ☺

Keep up the great work 🤘

**Comment by dattran92** [comment]
This should works. I'll add it in. Thanks!

**Comment by dattran92** [comment]
I pushed the fix https://github.com/dattran92/site-prerender/commit/12e5d4072f8ff65c7a381ec1201384dd62bc961b
